### ISSUE TITLE
Alt tags

### ISSUE THREAD

**Issue by conneralegre** [cesthree/prj-rev-bwfs-dasmoto#2]
Simplify - Add alt tags to your images. The purpose of alt attributes is to provide a description of the contents of an image file. 
https://github.com/cesthree/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/index.html#L38
https://github.com/cesthree/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/index.html#L44
https://github.com/cesthree/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/index.html#L50

**Comment by cesthree** [comment]
Added alt tags to img elements.
