### ISSUE TITLE
Div usage

### ISSUE THREAD

**Issue by conneralegre** [cesthree/prj-rev-bwfs-dasmoto#3]
Great! - You wrapped your code in divs in the proper locations and have your code sectioned out into them. 

https://github.com/cesthree/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/index.html#L36
https://github.com/cesthree/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/index.html#L42
https://github.com/cesthree/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/index.html#L48

**Comment by cesthree** [comment]
Thanks for the feedback!
