### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by conneralegre** [cesthree/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Project is working great! I liked how clean your markup was and how you sectioned it so it was easy to read over. Next time I would make sure to add alt tags to your images to aid in accessibility and so we have a good description of what the image is. The other thing is making sure you download the images and store them in a separate folder so the page will load faster and you don't have to rely on external servers. Next I would start working on learning flexbox (https://geddski.teachable.com/p/flexbox-zombies) and media queries (https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) to make your pages responsive

**Comment by cesthree** [comment]
Thanks much for the feedback! I will definitely use your recommendations in my future projects--as well as practicing by implementing them in my existing project.
